// See README.md for license details.

package vamps

import chisel3._

/**
  * This provides an alternate way to run tests, by executing then as a main
  * From sbt (Note: the test: prefix is because this main is under the test package hierarchy):
  * {{{
  * test:runMain vamps.MiVampsMain
  * }}}
  * To see all command line options use:
  * {{{
  * test:runMain vamps.MiVampsMain --help
  * }}}
  * To run with verilator:
  * {{{
  * test:runMain vamps.MiVampsMain --backend-name verilator
  * }}}
  * To run with verilator from your terminal shell use:
  * {{{
  * sbt 'test:runMain vamps.MiVampsMain --backend-name verilator'
  * }}}
  */
object MiVampsMain extends App {
  iotesters.Driver.execute(args, () => new MiVamps) {
    c => new MiVampsUnitTester(c)
  }
}

/**
  * This provides a way to run the firrtl-interpreter REPL (or shell)
  * on the lowered firrtl generated by your circuit. You will be placed
  * in an interactive shell. This can be very helpful as a debugging
  * technique. Type help to see a list of commands.
  *
  * To run from sbt
  * {{{
  * test:runMain vamps.MiVampsRepl
  * }}}
  * To run from sbt and see the half a zillion options try
  * {{{
  * test:runMain vamps.MiVampsRepl --help
  * }}}
  */
object MiVampsRepl extends App {
  iotesters.Driver.executeFirrtlRepl(args, () => new MiVamps)
}
